#!/bin/bash
#PBS -N conv2conv                              
#PBS -o out
#PBS -e err
#PBS -q mem64 
#PBS -l nodes=1:ppn=4     
cd $PBS_O_WORKDIR
echo '======================================================='
echo "Starting on `hostname` at `date`"
echo Working directory is $PBS_O_WORKDIR

alias python="python3"
#export OMP_NUM_THREADS=4 
#export I_MPI_PIN=disable
echo 'This job started on: ' `date`

mpirun  -np 4  python -u    main.py  >     log

echo '======================================================='
echo "Job Ended at `date`"
echo '======================================================='
